Service:
  greeting: Hello from client
  port: 8888
  spring.application.name: client
  eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
  eureka.client.service-url.healthcheck: true
  backserver.ribbon.eureka.enabled: true
  backserver.ribbon.ServerListRefreshInterval: 2000
  backserver.ribbon.listOfServers: localhost:8081,localhost:8082
  management.endpoints.web.exposure.include: hystrix.stream, info, health
  management.metrics.export.influx.uri: localhost:8088